run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gofmt
    - goimports
    - revive
    - unconvert
    - unparam

linters-settings:
  goimports:
    local-prefixes: github.com/wzhongyou/baize
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
  misspell:
    locale: US

issues:
  exclude-dirs:
    - vendor
    - web
    - .git
  exclude-files:
    - ".*_test\\.go$"
  max-issues-per-linter: 0
  max-same-issues: 0
